### ISSUE TITLE
Dataset documentation

### ISSUE THREAD

**Issue by alexmonti19** [chychen/BasketballGAN#1]
Hi,
is there any documentation regarding the four numpy arrays we can download from the dataset link?
It would help me understand how the data are stored/organized.

**Comment by chychen** [comment]
### BasketballGAN dataset

- Dataset: NBA 2015-2016 player tracking data (Half season)
- NBA 2015-2016 play-by-play data

### Data processing
Project dataset only contains offensive set plays of 1 ball and 10 players (5 on offence and 5 on defence) [x,y] positions, starting when the ball is dribbled across or in-bounded from the half court, and ends when a shot is made or missed.

1)	NBA play-by-play information is parsed along the tracking data to extract every shot made or missed in the player tracking data
2)	Record when offence brings ball pass half-court or inbounds at half-court (scoring end)
3)	End recorded segment when ball is shot by player (miss or made)
4)	Down sample data to 5 frames per second.
5)    We use Ramer-Douglas-Peuker algorithm to simply the real offense sequence as the conditions(sketches) fed into generator.

**Comment by alexmonti19** [comment]
Hi, thanks for your response!

> Project dataset only contains offensive set plays of 1 ball and 10 players (5 on offence and 5 on defence) [x,y] positions, starting when the ball is dribbled across or in-bounded from the half court, and ends when a shot is made or missed

Ok, now the shape of the first array makes sense :) 
'50Real.npy' -> 14k+ different sequences, 50 timesteps per sequence, and the position of the 10 players + the ball for every timestep


What about the other three arrays? In the Drive folder I also found '50Seq.npy' (14032x50x12), 'SeqReal.npy' (14032x50x6) and 'SeqCond.npy' (14032x50x6), and I'm struggling to understand what they may contain.

**Comment by chychen** [comment]
sorry for the bad naming styles.
50Real.npy -> real play
50Seq.npy -> real offensive strategies
SeqReal.npy -> one hot format, ball status for real play
SeqCond.npy -> one hot format, ball status for real offensive strategies

one hot format: (6 dims)
0-> offense player0 has the ball,
1-> offense player1 has the ball,
...
5 -> no one has the ball (shooting or passing)

**Comment by alexmonti19** [comment]
> SeqReal.npy -> one hot format, ball status for real play
> SeqCond.npy -> one hot format, ball status for real offensive strategies
> 
> one hot format: (6 dims)
> 0-> offense player0 has the ball,
> 1-> offense player1 has the ball,
> ...
> 5 -> no one has the ball (shooting or passing)

Perfect :)

> 50Seq.npy -> real offensive strategies

Mmh, so, for this one, what does the last dim (=12) represent?

**Comment by chychen** [comment]
ball (x,y) + 5 offensive players (x,y)  = 1*2 + 5*2 = 12

**Comment by alexmonti19** [comment]
Thank you again :)

**Comment by DerekRoy** [comment]
Following up on this, how do you actually predict on this code? Is it the game_visualizer.py file, and if so what is the  "../..data/FEATURES-4.npy" meant to be.
