### ISSUE TITLE
How do you run the GAN? 

### ISSUE THREAD

**Issue by DerekRoy** [chychen/BasketballGAN#2]
After we finish training and have a model, how are we meant to run predictions? I'm assuming it is the game_visualizer.py file, if that is the case what is the "../..data/FEATURES-4.npy" meant to be? Any guidance on this would be appreciated. 

As a follow up, am I able to create the same kind of output as the first gif in the read me? Or is that not published in this github?

**Comment by chychen** [comment]
sorry I think part of code are missing, and we don't plan to refactor this repo, maybe you could refer on branch UI, where you should be able to run up the ui system, and the system will inference results based on trained model, and you could get the idea how to load the trained model.

**Comment by DerekRoy** [comment]
Thank you that branch had what was necessary to set up the UI. Is there anyway to make the UI more reliable? Currently the ball does not track with the player when I move them, and as such it is very easy to get an out of bounds error due to the ballx1 and bally1 array not being as large as the index of time-1. Is there anywhere in the code you could recommend I go to fix this?

**Comment by chychen** [comment]
> Currently the ball does not track with the player when I move them
> very easy to get an out of bounds error

yes, very sorry for this, the code is written by students just for demo, and the maintainer is not available. Even so, I am sure it could be run by carefully following the instruction in [ui-user-guide](https://github.com/chychen/BasketballGAN/tree/UI/UI#ui-user-guide)

**Comment by DerekRoy** [comment]
Thanks for the feed back, it does work just with very specific methods.
